---
- name: Setup layout
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
  - "{{ binaries }}"
  - "{{ downloads }}"
  - "{{ apps }}"
  - "{{ formations }}"
  - "{{ workspace }}"
